# k apply -f clip.fe.yml
#
# k delete svc fe
#
# curl fe.default
#
apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  type: ClusterIP
  selector:
    app: fe
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP