apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be
        # TODO
        # image: registry.digitalocean.com/snake/snake_be:latest
        image: snake_be:0.1
        ports:
        - name: http
          containerPort: 8000
